version: '3.8'
services:
  postgresql:
    # образ, из которого должен быть запущен контейнер
    image: postgres:16beta1-bullseye
    container_name: stats_database
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "6541:5432"

  server:
    build: stats/stats-server
    image: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    # "зависит от",
    depends_on:
      - postgresql
    # переменные окружения
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=stats
      - DB_USER=test
      - DB_PASS=test